/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aads.poo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // Carro c = new Carro();

        // System.out.println("Velocidade: " + c.obterVelocidade());

        // c.acelerar(10);

        // System.out.println("Velocidade: " + c.obterVelocidade());

        // d.acelerar(v);
        
        Scanner teclado = new Scanner(System.in);
        int valor;
        
        System.out.print("Entre com o valor que deseja: ");
        valor = teclado.nextInt();
        
        Contador v = new Contador();
        
        v.addValor(valor);

        v.cont();

        System.out.println("Valor do contador: " + v.valorCont());
    }
}
