/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // int valor;

        // Scanner teclado = new Scanner(System.in);
        // System.out.print("Entre com a velocidade de seu carro: ");

        // if(teclado.hasNextLine() && teclado.hasNextInt()){
        //     valor = teclado.nextInt();
        //     Carro c = new Carro(valor);
        // } else{
        //     Carro padrao = new Carro();
        // }

        Carro c = new Carro();
        System.out.println(c);
        c.acelarar(30);
        System.out.println(c);
        c.frear(20);
        System.out.println(c);

        Carro d = new Carro(100);
        System.out.println(d);
        d.acelarar(30);
        System.out.println(d);
        d.frear(10);
        System.out.println(d);

    }
}
