/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Ponto a = new Ponto(1, 2);
        Ponto b = new Ponto(3, 4);

        System.out.println(a.distacia(b));
        System.out.println(b.distacia(a));
        System.out.println(a.distacia(a));
    }
}
